config/routes.rb
Twitterbasic::Application.routes.draw do
  resources :follows

  resources :twitts

  match "home/index" => "home#index", :as => "home"

  devise_for :users

  match "wall/:user_id" => "home#user_wall", :as => "user_wall"

  resources :users
  post "search/" => "home#user_search", :as => "user_search"
  get "follow/:following_id" => "follows#follow", :as => "follow"
  get "un_follow/:following_id" => "follows#un_follow", :as => "un_follow"
  get "profile" => "home#profile", :as => "profile"

  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end

   root :to => 'home#index'

end

app/models/twitt.rb
class Twitt < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :post

end

app/controllers/twitts_controller.rb
class TwittsController < ApplicationController
  # GET /twitts
  # GET /twitts.json
  def index
    @twitts = Twitt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @twitts }
    end
  end

  # GET /twitts/1
  # GET /twitts/1.json
  def show
    @twitt = Twitt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @twitt }
    end
  end

  # GET /twitts/new
  # GET /twitts/new.json
  def new
    @twitt = Twitt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @twitt }
    end
  end

  # GET /twitts/1/edit
  def edit
    @twitt = Twitt.find(params[:id])
  end

  # POST /twitts
  # POST /twitts.json
  def create
    @twitt = Twitt.new(params[:twitt])
    @twitt.user_id = current_user.id

    respond_to do |format|
      if @twitt.save
        format.html { redirect_to root_path, notice: 'Twitt was successfully created.' }
        format.json { render json: @twitt, status: :created, location: @twitt }
      else
        format.html { render action: "new" }
        format.json { render json: @twitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /twitts/1
  # PUT /twitts/1.json
  def update
    @twitt = Twitt.find(params[:id])

    respond_to do |format|
      if @twitt.update_attributes(params[:twitt])
        format.html { redirect_to @twitt, notice: 'Twitt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @twitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitts/1
  # DELETE /twitts/1.json
  def destroy
    @twitt = Twitt.find(params[:id])
    @twitt.destroy

    respond_to do |format|
      format.html { redirect_to twitts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/twitts_helper.rb
module TwittsHelper
end

app/views/twitts/_form.html.erb
<%= form_for(@twitt) do |f| %>
  <% if @twitt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitt.errors.count, "error") %> prohibited this twitt from being saved:</h2>

      <ul>
      <% @twitt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_area :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitts/edit.html.erb
<h1>Editing twitt</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitt %> |
<%= link_to 'Back', twitts_path %>

app/views/twitts/index.html.erb
<h1>Listing twitts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @twitts.each do |twitt| %>
  <tr>
    <td><%= twitt.user.nick %></td>
    <td><%= twitt.post %></td>
    <td><%= link_to 'Show', twitt %></td>
    <td><%= link_to 'Edit', edit_twitt_path(twitt) %></td>
    <td><%= link_to 'Destroy', twitt, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Twitt', new_twitt_path %>

app/views/twitts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @twitt.user_id %>
</p>

<p>
  <b>Post:</b>
  <%= @twitt.post %>
</p>


<%= link_to 'Edit', edit_twitt_path(@twitt) %> |
<%= link_to 'Back', twitts_path %>