config/routes.rb
Twitterbasic::Application.routes.draw do
  resources :follows

  resources :twitts

  match "home/index" => "home#index", :as => "home"

  devise_for :users

  match "wall/:user_id" => "home#user_wall", :as => "user_wall"

  resources :users
  post "search/" => "home#user_search", :as => "user_search"
  get "follow/:following_id" => "follows#follow", :as => "follow"
  get "un_follow/:following_id" => "follows#un_follow", :as => "un_follow"
  get "profile" => "home#profile", :as => "profile"

  devise_scope :user do
    get "sign_out", :to => "devise/sessions#destroy"
  end

   root :to => 'home#index'

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :user, :foreign_key => :following_id
  belongs_to :twitt, :foreign_key => :user_id
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @follows }
    end
  end

  # GET /follows/1
  # GET /follows/1.json
  def show
    @follow = Follow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/new
  # GET /follows/new.json
  def new
    @follow = Follow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/1/edit
  def edit
    @follow = Follow.find(params[:id])
  end

  def follow
    if !Follow.where(:following_id => params[:following_id], :user_id => current_user.id).blank?
      redirect_to root_path
    else
      @follow = Follow.new(:following_id => params[:following_id], :user_id => current_user.id)
      if @follow.save
        redirect_to root_path
      else
        redirect_to root_path
      end
    end
  end

  def un_follow
    if Follow.where(:following_id => params[:following_id], :user_id => current_user.id).blank?
      redirect_to root_path
    else
      @follow = Follow.where(:following_id => params[:following_id], :user_id => current_user.id).first
      if @follow.destroy
        redirect_to root_path
      else
        redirect_to root_path
      end
    end
  end

  # POST /follows
  # POST /follows.json
  def create
    @follow = Follow.new(params[:follow])

    respond_to do |format|
      if @follow.save
        format.html { redirect_to @follow, notice: 'Follow was successfully created.' }
        format.json { render json: @follow, status: :created, location: @follow }
      else
        format.html { render action: "new" }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /follows/1
  # PUT /follows/1.json
  def update
    @follow = Follow.find(params[:id])

    respond_to do |format|
      if @follow.update_attributes(params[:follow])
        format.html { redirect_to @follow, notice: 'Follow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow = Follow.find(params[:id])
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to follows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follow_id %><br />
    <%= f.number_field :follow_id %>
  </div>
  <div class="field">
    <%= f.label :following_id %><br />
    <%= f.number_field :following_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>Listing follows</h1>

<table>
  <tr>
    <th>Follow</th>
    <th>Following</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @follows.each do |follow| %>
  <tr>
    <td><%= follow.follow_id %></td>
    <td><%= follow.following_id %></td>
    <td><%= link_to 'Show', follow %></td>
    <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
    <td><%= link_to 'Destroy', follow, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Follow:</b>
  <%= @follow.follow_id %>
</p>

<p>
  <b>Following:</b>
  <%= @follow.following_id %>
</p>


<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>